### ISSUE TITLE
Block quotes are not working

### ISSUE THREAD

**Issue by ffunenga** [mkdocs/mkdocs-bootswatch#65]
I installed mkdocs-bootswatch and tried several of the sub-themes, but the citations / block-quotes are showing up in the web browser. For example, the following md:

```
Hello, this is an example:

> And this is a citation

and this is a further paragraph.
```

results in the following:

![image](https://user-images.githubusercontent.com/2396815/80185408-9376fe00-860c-11ea-9ab7-d4f18c44f056.png)

In this example, I have used the `yeti` subtheme.

**Comment by jamesonl** [comment]
Hello - I am also experiencing the same issue.

**Comment by jamesonl** [comment]
Hey @ffunenga , I was able to address this by switching the theme to the material version. You might consider doing the same, as my block quotes appear to be working fine there.

https://github.com/squidfunk/mkdocs-material

**Comment by fu-sen** [comment]
This is due to a change in Bootstrap specifications. From Bootstrap 4, the usage of `<blockquote>` has changed.
https://getbootstrap.com/docs/4.5/content/typography/#blockquotes

**Comment by techabstraction** [comment]
I have this issue also and am using the material theme

**Comment by raymondberg** [comment]
Adding some custom CSS in your configuration is a decent workaround for this in the short-term. Example: 

```yaml
# mkdocs.yml

# ... your config

extra_css:     
  - some.css
```

```css
# some.css

blockquote {              
  background-color: black;
  font-style: italic;     
  color: white;           
  padding: 1em;           
}                         
```

And, of course, style to taste.
